name: Build TASH
"on":
  pull_request:
    branches:
      - main
    paths:
      - 'tash/**'
  push:
    branches:
      - main
    paths:
      - 'tash/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go environment
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: tash/go.mod
          cache: false

      - name: Test
        working-directory: tash
        run: go test

      - name: Build
        working-directory: tash
        run: go build

      - name: Build darwin arm64
        working-directory: tash
        run: GOOS=darwin GOARCH=arm64 go build -o tash-darwin-arm64

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          make_latest: true
          name: Latest release
          body: Stable rolling release
          tag_name: latest
          generate_release_notes: false
          files: |
            tash/tash
            tash/tash-darwin-arm64
